name: Clang Tidy

on:
  push:
    branches:
      - main
  pull_request:

env:
  CLANG_TIDY: clang-tidy-15
  RUN_CLANG_TIDY: run-clang-tidy-15

jobs:
  tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Install clang-tidy
      run: |
        sudo apt update
        sudo apt -y install clang-tidy-15 

    - uses: actions/checkout@v2

    - name: Run clang-tidy
      run: bash scripts/clang-tidy.sh

