name: Clang Format

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.15
      with:
        source: 'benchmarks'
        extensions: 'hpp,cpp'
        clangFormatVersion: 15
